/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthRouteRouteImport } from "./routes/auth/route";
import { Route as RouteRouteImport } from "./routes/route";
import { Route as AuthSignupRouteImport } from "./routes/auth/signup";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const RouteRoute = RouteRouteImport.update({
  id: "/",
  path: "",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/auth": typeof AuthRouteRouteWithChildren;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/signup": typeof AuthSignupRoute;
}
export interface FileRoutesByTo {
  "/auth": typeof AuthRouteRouteWithChildren;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/signup": typeof AuthSignupRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof RouteRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/signup": typeof AuthSignupRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/auth" | "/auth/login" | "/auth/signup";
  fileRoutesByTo: FileRoutesByTo;
  to: "/auth" | "/auth/login" | "/auth/signup";
  id: "__root__" | "/" | "/auth" | "/auth/login" | "/auth/signup";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof RouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/signup": {
      id: "/auth/signup";
      path: "/signup";
      fullPath: "/auth/signup";
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(AuthRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
